uploads = []
generated = []

[[outputs]]
id = "rBD0L8oyTa7tMvP0SkNiK"
uri = "file://UPDATE_NOTES.md"
type = "text"
title = "LabTrax Build Update Notes - v1.0.3 Build 31"

[[outputs]]
id = "zCj5OH5xCkmS2vQ535MV3"
uri = "file://APP_STORE_LISTING.md"
type = "text"
title = "LabTrax - Apple App Store Promotional Text"

[[outputs]]
id = "keJU1HUHccipZH8fBMmB9"
uri = "file://labtrax-source-code.tar.gz"
type = "unspecified"
title = "LabTrax Source Code"

[[outputs]]
id = "9zst1VvP1V3D9mmoHbBIN"
uri = "file://labtrax-full-source.tar.gz"
type = "unspecified"
title = "LabTrax Full Source Code (v1.0.6)"

[[outputs]]
id = "ZQs1OTEjuxqIbCx8hegVY"
uri = "file://labtrax-source.tar.gz"
type = "unspecified"
title = "LabTrax Source Code (v1.0.6, build 51)"

[[outputs]]
id = "GmO8hYcumOEvrz4n2G1HV"
uri = "file://exports/labtrax-source.zip"
type = "unspecified"
title = "LabTrax Source Code"
