/**
 * Provider-portal foundation tests (Account epic Phase 5).
 *
 * Skipped when DATABASE_URL is not configured. All inserted rows are removed
 * in afterAll so the suite is safe to run against a shared dev DB.
 *
 * Proves the Phase 5 guarantees:
 *  - Provider signup issues a platform account number in the `P-...` family.
 *  - Provider signup with createOrganization creates a `provider`-type org.
 *  - GET /api/cases/provider is strictly scoped to the caller's own provider
 *    org(s): a provider sees only their assigned cases, never another
 *    provider's, and a lab user gets an empty list.
 *  - Cross-tenant reads are denied on every surface: the dedicated provider
 *    list, the bare /api/cases list, the `?organizationId=` filter (IDOR), and
 *    case detail.
 *  - claimProvider signup creates an active membership immediately so the
 *    provider sees their lab's cases without waiting for admin approval.
 *  - A provider linked to two labs via doctor_account_links sees cases from
 *    both labs on GET /api/cases/provider.
 *  - New provider account numbers generated by POST /api/organizations include
 *    the parent lab's acronym prefix (e.g. "TL-BC-1").
 *  - Existing account numbers without a prefix continue to resolve correctly.
 */
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { createHash, randomBytes } from "node:crypto";
import { inArray, eq, or } from "drizzle-orm";
import request from "supertest";
import * as path from "node:path";

vi.mock("../lib/backup.js", () => ({
  restartScheduledBackupJob: vi.fn().mockResolvedValue(undefined),
}));
vi.mock("../lib/billing-jobs.js", () => ({ startBillingJobs: vi.fn() }));
vi.mock("../lib/statements.js", () => ({ startStatementScheduler: vi.fn() }));
vi.mock("../lib/case-media.js", () => ({
  startDailyOrphanedMediaCleanup: vi.fn(),
  caseMediaDir: path.join(require("os").tmpdir(), "labtrax-test-media-provider"),
  extractMediaFileName: () => null,
}));

const SHOULD_RUN = !!process.env["DATABASE_URL"];
const maybe = SHOULD_RUN ? describe : describe.skip;

function rid(prefix: string) {
  return `${prefix}_${randomBytes(8).toString("hex")}`;
}

maybe("Provider portal foundation (db integration)", () => {
  let dbMod: typeof import("@workspace/db");
  let appMod: { default: import("express").Express };
  let authLib: typeof import("../lib/auth.js");

  const labOwnerId = rid("u");
  const providerUserAId = rid("u");
  const providerUserBId = rid("u");

  const labOrgId = rid("lab");
  const providerOrgAId = rid("prov");
  const providerOrgBId = rid("prov");

  const createdCaseIds: string[] = [];
  // Users/orgs created by the register endpoint test, cleaned up in afterAll.
  const registeredUserIds: string[] = [];
  const registeredOrgIds: string[] = [];

  let caseAId = "";
  let caseBId = "";

  async function makeSession(userId: string): Promise<{ access: string }> {
    const { db, userSessions } = dbMod as any;
    const sessionId = rid("sess");
    const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
    const refresh = authLib.signRefreshToken(userId, sessionId);
    const hash = createHash("sha256").update(refresh).digest("hex");
    await db
      .insert(userSessions)
      .values({ id: sessionId, userId, tokenHash: hash, expiresAt });
    const access = authLib.signAccessToken(userId, sessionId);
    return { access };
  }

  async function createCase(
    access: string,
    providerOrgId: string,
    patient: string
  ): Promise<string> {
    const r = await request(appMod.default)
      .post("/api/cases")
      .set("Authorization", `Bearer ${access}`)
      .send({
        caseNumber: rid("CN"),
        labOrganizationId: labOrgId,
        providerOrganizationId: providerOrgId,
        patientFirstName: patient,
        patientLastName: "Test",
        doctorName: "Dr. Provider",
        status: "received",
      });
    expect(r.status).toBe(201);
    const id = r.body.data.id as string;
    createdCaseIds.push(id);
    return id;
  }

  beforeAll(async () => {
    process.env["JWT_SECRET"] =
      process.env["JWT_SECRET"] ?? "labtrax-test-secret-provider";
    dbMod = await import("@workspace/db");
    appMod = await import("../app.js");
    authLib = await import("../lib/auth.js");

    const { db, users, organizations, organizationMemberships } = dbMod as any;

    await db.insert(users).values([
      { id: labOwnerId, username: `labowner_${labOwnerId}`, password: "x", userType: "lab" },
      {
        id: providerUserAId,
        username: `prova_${providerUserAId}`,
        password: "x",
        userType: "provider",
      },
      {
        id: providerUserBId,
        username: `provb_${providerUserBId}`,
        password: "x",
        userType: "provider",
      },
    ]);

    await db.insert(organizations).values([
      { id: labOrgId, type: "lab", name: rid("ProvTestLab") },
      {
        id: providerOrgAId,
        type: "provider",
        name: rid("PracticeA"),
        parentLabOrganizationId: labOrgId,
      },
      {
        id: providerOrgBId,
        type: "provider",
        name: rid("PracticeB"),
        parentLabOrganizationId: labOrgId,
      },
    ]);

    await db.insert(organizationMemberships).values([
      {
        id: rid("m"),
        labId: labOrgId,
        userId: labOwnerId,
        role: "owner",
        status: "active",
        approvedByUserId: labOwnerId,
        joinedAt: new Date(),
      },
      {
        id: rid("m"),
        labId: providerOrgAId,
        userId: providerUserAId,
        role: "owner",
        status: "active",
        approvedByUserId: providerUserAId,
        joinedAt: new Date(),
      },
      {
        id: rid("m"),
        labId: providerOrgBId,
        userId: providerUserBId,
        role: "owner",
        status: "active",
        approvedByUserId: providerUserBId,
        joinedAt: new Date(),
      },
    ]);

    // Cases are created by the lab owner (member of the lab) and assigned to
    // each provider org.
    const { access } = await makeSession(labOwnerId);
    caseAId = await createCase(access, providerOrgAId, "AlphaPatient");
    caseBId = await createCase(access, providerOrgBId, "BetaPatient");
  });

  // Ensure a fresh session exists before each test; per-test sessions created
  // in each it() body are still the authoritative token for that test.
  beforeEach(async () => {
    await makeSession(labOwnerId);
  });

  afterAll(async () => {
    if (!SHOULD_RUN) return;
    const {
      db,
      auditLogs,
      caseEvents,
      caseNotes,
      caseRestorations,
      invoices,
      cases: casesTable,
      userSessions,
      organizationMemberships,
      organizations,
      users,
    } = dbMod as any;

    const allUserIds = [
      labOwnerId,
      providerUserAId,
      providerUserBId,
      ...registeredUserIds,
    ];
    const allOrgIds = [
      labOrgId,
      providerOrgAId,
      providerOrgBId,
      ...registeredOrgIds,
    ];

    if (createdCaseIds.length) {
      await db.delete(caseEvents).where(inArray(caseEvents.caseId, createdCaseIds));
      await db.delete(caseNotes).where(inArray(caseNotes.caseId, createdCaseIds));
      await db
        .delete(caseRestorations)
        .where(inArray(caseRestorations.caseId, createdCaseIds));
      await db.delete(invoices).where(inArray(invoices.caseId, createdCaseIds));
    }
    await db.delete(auditLogs).where(inArray(auditLogs.organizationId, allOrgIds));
    await db.delete(invoices).where(inArray(invoices.labOrganizationId, [labOrgId]));
    await db.delete(casesTable).where(inArray(casesTable.labOrganizationId, [labOrgId]));
    await db.delete(userSessions).where(inArray(userSessions.userId, allUserIds));
    await db
      .delete(organizationMemberships)
      .where(inArray(organizationMemberships.userId, allUserIds));
    await db.delete(organizations).where(inArray(organizations.id, allOrgIds));
    await db.delete(users).where(inArray(users.id, allUserIds));
  });

  // ── Provider signup ───────────────────────────────────────────────────────

  it("provider signup issues a P- account number and a provider org", async () => {
    const uname = `psig${randomBytes(3).toString("hex")}`;
    const r = await request(appMod.default)
      .post("/api/auth/register")
      .send({
        username: uname,
        password: "Sup3rSecret!",
        email: `${uname}@example.com`,
        userType: "provider",
        practiceName: rid("SignupPractice"),
        createOrganization: true,
        clientType: "desktop",
      });

    expect(r.status).toBe(200);
    expect(r.body.success).toBe(true);
    const acct: string = r.body.user?.platformAccountNumber ?? "";
    expect(acct.startsWith("P-")).toBe(true);

    if (r.body.user?.id) registeredUserIds.push(r.body.user.id);
    const orgId: string | undefined = r.body.organization?.id;
    expect(orgId).toBeTruthy();
    if (orgId) {
      registeredOrgIds.push(orgId);
      const { db, organizations } = dbMod as any;
      const org = await db.query.organizations.findFirst({
        where: eq(organizations.id, orgId),
      });
      expect(org?.type).toBe("provider");
    }
  });

  // ── GET /api/cases/provider scoping ────────────────────────────────────────

  it("provider A sees only their own assigned cases", async () => {
    const { access } = await makeSession(providerUserAId);
    const r = await request(appMod.default)
      .get("/api/cases/provider")
      .set("Authorization", `Bearer ${access}`);
    expect(r.status).toBe(200);
    const ids: string[] = (r.body.data ?? []).map((c: any) => c.id);
    expect(ids).toContain(caseAId);
    expect(ids).not.toContain(caseBId);
  });

  it("provider B sees only their own assigned cases", async () => {
    const { access } = await makeSession(providerUserBId);
    const r = await request(appMod.default)
      .get("/api/cases/provider")
      .set("Authorization", `Bearer ${access}`);
    expect(r.status).toBe(200);
    const ids: string[] = (r.body.data ?? []).map((c: any) => c.id);
    expect(ids).toContain(caseBId);
    expect(ids).not.toContain(caseAId);
  });

  it("a lab user gets an empty provider list", async () => {
    const { access } = await makeSession(labOwnerId);
    const r = await request(appMod.default)
      .get("/api/cases/provider")
      .set("Authorization", `Bearer ${access}`);
    expect(r.status).toBe(200);
    expect(r.body.data).toEqual([]);
  });

  it("unauthenticated GET /api/cases/provider returns 401", async () => {
    const r = await request(appMod.default).get("/api/cases/provider");
    expect(r.status).toBe(401);
  });

  // ── Cross-tenant isolation ─────────────────────────────────────────────────

  it("bare /api/cases for provider A excludes provider B's cases", async () => {
    const { access } = await makeSession(providerUserAId);
    const r = await request(appMod.default)
      .get("/api/cases")
      .set("Authorization", `Bearer ${access}`);
    expect(r.status).toBe(200);
    const ids: string[] = (r.body.data ?? []).map((c: any) => c.id);
    expect(ids).toContain(caseAId);
    expect(ids).not.toContain(caseBId);
  });

  it("provider A cannot read another provider org via ?organizationId (IDOR)", async () => {
    const { access } = await makeSession(providerUserAId);
    const r = await request(appMod.default)
      .get(`/api/cases?organizationId=${providerOrgBId}`)
      .set("Authorization", `Bearer ${access}`);
    expect(r.status).toBe(403);
  });

  it("provider A cannot read the lab org via ?organizationId (IDOR)", async () => {
    const { access } = await makeSession(providerUserAId);
    const r = await request(appMod.default)
      .get(`/api/cases?organizationId=${labOrgId}`)
      .set("Authorization", `Bearer ${access}`);
    expect(r.status).toBe(403);
  });

  it("provider A can read their own org via ?organizationId", async () => {
    const { access } = await makeSession(providerUserAId);
    const r = await request(appMod.default)
      .get(`/api/cases?organizationId=${providerOrgAId}`)
      .set("Authorization", `Bearer ${access}`);
    expect(r.status).toBe(200);
    const ids: string[] = (r.body.data ?? []).map((c: any) => c.id);
    expect(ids).toContain(caseAId);
  });

  it("provider A can read their own case detail", async () => {
    const { access } = await makeSession(providerUserAId);
    const r = await request(appMod.default)
      .get(`/api/cases/${caseAId}`)
      .set("Authorization", `Bearer ${access}`);
    expect(r.status).toBe(200);
    expect(r.body.data.id).toBe(caseAId);
  });

  it("provider A cannot read provider B's case detail", async () => {
    const { access } = await makeSession(providerUserAId);
    const r = await request(appMod.default)
      .get(`/api/cases/${caseBId}`)
      .set("Authorization", `Bearer ${access}`);
    expect([403, 404]).toContain(r.status);
  });

  // ── claimProvider auto-approval ────────────────────────────────────────────

  it("claimProvider signup creates active membership — provider sees cases immediately", async () => {
    const { db, users, organizations, organizationMemberships, cases: casesTable, userSessions } = dbMod as any;

    // Create a lab + provider org with a known account number.
    const claimLabId = rid("lab");
    const claimProvOrgId = rid("prov");
    const claimLabOwnerId = rid("u");
    const claimAcct = rid("ACCT");

    await db.insert(users).values({ id: claimLabOwnerId, username: `clo_${claimLabOwnerId}`, password: "x", userType: "lab" });
    await db.insert(organizations).values([
      { id: claimLabId, type: "lab", name: rid("ClaimTestLab") },
      { id: claimProvOrgId, type: "provider", name: rid("ClaimPractice"), parentLabOrganizationId: claimLabId, accountNumber: claimAcct },
    ]);
    await db.insert(organizationMemberships).values({
      id: rid("m"), labId: claimLabId, userId: claimLabOwnerId, role: "owner", status: "active", approvedByUserId: claimLabOwnerId, joinedAt: new Date(),
    });

    // Create a case assigned to the provider org BEFORE the provider signs up.
    const { access: labAccess } = await makeSession(claimLabOwnerId);
    const caseR = await request(appMod.default)
      .post("/api/cases")
      .set("Authorization", `Bearer ${labAccess}`)
      .send({
        caseNumber: rid("CN"),
        labOrganizationId: claimLabId,
        providerOrganizationId: claimProvOrgId,
        patientFirstName: "ClaimPatient",
        patientLastName: "Test",
        doctorName: "Dr. Claim",
        status: "received",
      });
    expect(caseR.status).toBe(201);
    const claimCaseId = caseR.body.data.id as string;
    createdCaseIds.push(claimCaseId);

    // Provider signs up using claimProvider — account number is the credential.
    const uname = `cp${randomBytes(3).toString("hex")}`;
    const regR = await request(appMod.default)
      .post("/api/auth/register")
      .send({
        username: uname,
        password: "Sup3rSecret!",
        email: `${uname}@example.com`,
        userType: "provider",
        claimProvider: { labId: claimLabId, accountNumber: claimAcct },
        clientType: "desktop",
      });
    expect(regR.status).toBe(200);
    const claimUserId: string = regR.body.user?.id;
    expect(claimUserId).toBeTruthy();
    registeredUserIds.push(claimUserId);

    // Mark the account as email-verified so requireVerifiedAccount passes.
    // (New canonical accounts have a P-YYYY-N number and require at least one
    // verified contact before accessing PHI via the cases endpoint.)
    await db.update(users).set({ emailVerifiedAt: new Date() }).where(eq(users.id, claimUserId));

    // The provider must be able to see the case immediately — no admin approval needed.
    const claimSess = await makeSession(claimUserId);
    const listR = await request(appMod.default)
      .get("/api/cases/provider")
      .set("Authorization", `Bearer ${claimSess.access}`);
    expect(listR.status).toBe(200);
    const ids: string[] = (listR.body.data ?? []).map((c: any) => c.id);
    expect(ids).toContain(claimCaseId);

    // Cleanup — delete invoices (auto-created on case POST) before orgs.
    const { invoices } = dbMod as any;
    if (invoices) {
      await db.delete(invoices).where(eq(invoices.providerOrganizationId, claimProvOrgId));
    }
    await db.delete(casesTable).where(eq(casesTable.id, claimCaseId));
    await db.delete(userSessions).where(eq(userSessions.userId, claimUserId));
    await db.delete(organizationMemberships).where(eq(organizationMemberships.userId, claimUserId));
    await db.delete(organizationMemberships).where(eq(organizationMemberships.userId, claimLabOwnerId));
    await db.delete(organizations).where(eq(organizations.id, claimProvOrgId));
    await db.delete(organizations).where(eq(organizations.id, claimLabId));
    await db.delete(users).where(eq(users.id, claimLabOwnerId));
  });

  // ── Cross-lab provider case visibility ────────────────────────────────────

  it("provider linked to two labs sees cases from both via doctor_account_links", async () => {
    const { db, users, organizations, organizationMemberships, doctorAccountLinks, cases: casesTable, userSessions } = dbMod as any;
    if (!doctorAccountLinks) {
      // Skip if the table export isn't available in this environment.
      return;
    }

    const labAId = rid("lab");
    const labBId = rid("lab");
    const provOrgAId = rid("prov");
    const provOrgBId = rid("prov");
    const labOwnerAId = rid("u");
    const labOwnerBId = rid("u");
    const docUserAId = rid("u");
    const docUserBId = rid("u");
    const xCaseAId = rid("xc");
    const xCaseBId = rid("xc");

    await db.insert(users).values([
      { id: labOwnerAId, username: `xloa_${labOwnerAId}`, password: "x", userType: "lab" },
      { id: labOwnerBId, username: `xlob_${labOwnerBId}`, password: "x", userType: "lab" },
      { id: docUserAId, username: `xdoca_${docUserAId}`, password: "x", userType: "provider" },
      { id: docUserBId, username: `xdocb_${docUserBId}`, password: "x", userType: "provider" },
    ]);
    await db.insert(organizations).values([
      { id: labAId, type: "lab", name: rid("XLabA") },
      { id: labBId, type: "lab", name: rid("XLabB") },
      { id: provOrgAId, type: "provider", name: rid("XPracticeA"), parentLabOrganizationId: labAId },
      { id: provOrgBId, type: "provider", name: rid("XPracticeB"), parentLabOrganizationId: labBId },
    ]);
    await db.insert(organizationMemberships).values([
      { id: rid("m"), labId: labAId, userId: labOwnerAId, role: "owner", status: "active", approvedByUserId: labOwnerAId, joinedAt: new Date() },
      { id: rid("m"), labId: labBId, userId: labOwnerBId, role: "owner", status: "active", approvedByUserId: labOwnerBId, joinedAt: new Date() },
      { id: rid("m"), labId: provOrgAId, userId: docUserAId, role: "owner", status: "active", approvedByUserId: docUserAId, joinedAt: new Date() },
      { id: rid("m"), labId: provOrgBId, userId: docUserBId, role: "owner", status: "active", approvedByUserId: docUserBId, joinedAt: new Date() },
    ]);

    // Link the two doctor accounts.
    const [low, high] = docUserAId < docUserBId ? [docUserAId, docUserBId] : [docUserBId, docUserAId];
    await db.insert(doctorAccountLinks).values({ id: rid("dal"), userIdLow: low, userIdHigh: high, linkedVia: "admin_backfill" });

    // Create one case per lab assigned to the respective provider org.
    const { access: accessA } = await makeSession(labOwnerAId);
    const caseAR = await request(appMod.default)
      .post("/api/cases")
      .set("Authorization", `Bearer ${accessA}`)
      .send({ caseNumber: rid("CN"), labOrganizationId: labAId, providerOrganizationId: provOrgAId, patientFirstName: "XPatA", patientLastName: "Test", doctorName: "Dr. X", status: "received" });
    expect(caseAR.status).toBe(201);
    createdCaseIds.push(caseAR.body.data.id);

    const { access: accessB } = await makeSession(labOwnerBId);
    const caseBR = await request(appMod.default)
      .post("/api/cases")
      .set("Authorization", `Bearer ${accessB}`)
      .send({ caseNumber: rid("CN"), labOrganizationId: labBId, providerOrganizationId: provOrgBId, patientFirstName: "XPatB", patientLastName: "Test", doctorName: "Dr. X", status: "received" });
    expect(caseBR.status).toBe(201);
    createdCaseIds.push(caseBR.body.data.id);

    // docUserA should see both cases (their own + linked B's).
    const { access: docAccessA } = await makeSession(docUserAId);
    const listR = await request(appMod.default)
      .get("/api/cases/provider")
      .set("Authorization", `Bearer ${docAccessA}`);
    expect(listR.status).toBe(200);
    const ids: string[] = (listR.body.data ?? []).map((c: any) => c.id);
    expect(ids).toContain(caseAR.body.data.id);
    expect(ids).toContain(caseBR.body.data.id);

    // Cleanup — must delete invoices (auto-created by POST /api/cases) before
    // deleting provider orgs, or the FK constraint on invoices.provider_organization_id
    // will reject the org delete.
    const { invoices } = dbMod as any;
    await db.delete(casesTable).where(eq(casesTable.id, caseAR.body.data.id));
    await db.delete(casesTable).where(eq(casesTable.id, caseBR.body.data.id));
    if (invoices) {
      await db.delete(invoices).where(or(
        eq(invoices.providerOrganizationId, provOrgAId),
        eq(invoices.providerOrganizationId, provOrgBId)
      ));
    }
    try { await db.delete(doctorAccountLinks).where(eq(doctorAccountLinks.userIdLow, low)); } catch {}
    await db.delete(userSessions).where(eq(userSessions.userId, docUserAId));
    await db.delete(userSessions).where(eq(userSessions.userId, docUserBId));
    await db.delete(organizationMemberships).where(eq(organizationMemberships.userId, docUserAId));
    await db.delete(organizationMemberships).where(eq(organizationMemberships.userId, docUserBId));
    await db.delete(organizationMemberships).where(eq(organizationMemberships.userId, labOwnerAId));
    await db.delete(organizationMemberships).where(eq(organizationMemberships.userId, labOwnerBId));
    await db.delete(organizations).where(eq(organizations.id, provOrgAId));
    await db.delete(organizations).where(eq(organizations.id, provOrgBId));
    await db.delete(organizations).where(eq(organizations.id, labAId));
    await db.delete(organizations).where(eq(organizations.id, labBId));
    await db.delete(users).where(inArray(users.id, [labOwnerAId, labOwnerBId, docUserAId, docUserBId]));
  });

  // ── Lab-acronym account number prefix ─────────────────────────────────────

  it("new provider account number created via POST /api/organizations includes lab acronym prefix", async () => {
    const { db, users, organizations: orgsTable, organizationMemberships, userSessions } = dbMod as any;

    // Create a lab with a distinctive multi-word name so the acronym is testable.
    const acroLabId = rid("lab");
    const acroLabOwnerId = rid("u");
    const labName = "Test Lab";  // acronym = "TL"

    await db.insert(users).values({ id: acroLabOwnerId, username: `alo_${acroLabOwnerId}`, password: "x", userType: "lab", emailVerifiedAt: new Date() });
    await db.insert(orgsTable).values({ id: acroLabId, type: "lab", name: labName, displayName: labName });
    await db.insert(organizationMemberships).values({
      id: rid("m"), labId: acroLabId, userId: acroLabOwnerId, role: "owner", status: "active", approvedByUserId: acroLabOwnerId, joinedAt: new Date(),
    });

    const { access } = await makeSession(acroLabOwnerId);
    const r = await request(appMod.default)
      .post("/api/organizations")
      .set("Authorization", `Bearer ${access}`)
      .send({
        type: "provider",
        name: rid("AcroPractice"),
        parentLabOrganizationId: acroLabId,
        doctorName: "Dr. Baker Collins",
        addressLine1: "456 Oak Ave",
      });
    expect(r.status).toBe(201);

    const createdOrg = r.body.data ?? r.body;
    const acct: string = createdOrg?.accountNumber ?? "";
    // Account number must start with the lab acronym "TL".
    expect(acct).toMatch(/^TL-/);

    // Cleanup
    if (createdOrg?.id) {
      await db.delete(orgsTable).where(eq(orgsTable.id, createdOrg.id));
    }
    await db.delete(userSessions).where(eq(userSessions.userId, acroLabOwnerId));
    await db.delete(organizationMemberships).where(eq(organizationMemberships.userId, acroLabOwnerId));
    await db.delete(orgsTable).where(eq(orgsTable.id, acroLabId));
    await db.delete(users).where(eq(users.id, acroLabOwnerId));
  });

  it("GET /api/cases/provider response includes providerAccountNumber and labName per case", async () => {
    // Use the existing providerUserAId / providerOrgAId / caseAId fixtures.
    // The provider org was created without an accountNumber in beforeAll, so
    // we patch one in for this assertion.
    const { db, organizations: orgsTable } = dbMod as any;
    const testAcct = rid("TA");
    await db.update(orgsTable).set({ accountNumber: testAcct }).where(eq(orgsTable.id, providerOrgAId));

    const { access } = await makeSession(providerUserAId);
    const r = await request(appMod.default)
      .get("/api/cases/provider")
      .set("Authorization", `Bearer ${access}`);
    expect(r.status).toBe(200);
    const foundCase = (r.body.data ?? []).find((c: any) => c.id === caseAId);
    expect(foundCase).toBeTruthy();
    expect(foundCase?.providerAccountNumber).toBe(testAcct);
    // labName should be a non-empty string (the test lab's name).
    expect(typeof foundCase?.labName).toBe("string");
    expect(foundCase?.labName?.length).toBeGreaterThan(0);

    // Restore
    await db.update(orgsTable).set({ accountNumber: null }).where(eq(orgsTable.id, providerOrgAId));
  });

  // ── Alias compatibility: raw input matches prefixed stored number ──────────

  it("claimProvider accepts unprefixed account number when stored value carries a lab acronym prefix", async () => {
    const { db, users, organizations, organizationMemberships, userSessions } = dbMod as any;

    // Set up a lab + provider org whose stored accountNumber has a prefix.
    const aliasLabId = rid("lab");
    const aliasPracticeId = rid("prov");
    const aliasLabOwnerId = rid("u");
    const rawNumber = rid("ALIAS");
    const prefixedNumber = `SDR-${rawNumber}`;

    await db.insert(users).values({
      id: aliasLabOwnerId, username: `alo2_${aliasLabOwnerId}`, password: "x", userType: "lab",
    });
    await db.insert(organizations).values([
      { id: aliasLabId, type: "lab", name: rid("AliasLab") },
      { id: aliasPracticeId, type: "provider", name: rid("AliasPractice"), parentLabOrganizationId: aliasLabId, accountNumber: prefixedNumber },
    ]);
    await db.insert(organizationMemberships).values({
      id: rid("m"), labId: aliasLabId, userId: aliasLabOwnerId, role: "owner", status: "active", approvedByUserId: aliasLabOwnerId, joinedAt: new Date(),
    });

    // Sign up using the RAW (unprefixed) account number as the credential.
    const uname = `alias${randomBytes(3).toString("hex")}`;
    const regR = await request(appMod.default)
      .post("/api/auth/register")
      .send({
        username: uname,
        password: "Sup3rSecret!",
        email: `${uname}@example.com`,
        userType: "provider",
        claimProvider: { labId: aliasLabId, accountNumber: rawNumber },
        clientType: "desktop",
      });
    // Must succeed — raw suffix resolves to the prefixed stored value.
    expect(regR.status).toBe(200);
    const aliasUserId: string = regR.body.user?.id;
    expect(aliasUserId).toBeTruthy();
    registeredUserIds.push(aliasUserId);

    // Must be linked to the correct practice (active membership).
    const memberRows = await db
      .select()
      .from(organizationMemberships)
      .where(eq(organizationMemberships.userId, aliasUserId));
    const memberOrgIds = memberRows.map((m: any) => m.labId);
    expect(memberOrgIds).toContain(aliasPracticeId);

    // Cleanup
    await db.delete(userSessions).where(eq(userSessions.userId, aliasUserId));
    await db.delete(organizationMemberships).where(eq(organizationMemberships.userId, aliasUserId));
    await db.delete(organizationMemberships).where(eq(organizationMemberships.userId, aliasLabOwnerId));
    await db.delete(organizations).where(eq(organizations.id, aliasPracticeId));
    await db.delete(organizations).where(eq(organizations.id, aliasLabId));
    await db.delete(users).where(eq(users.id, aliasLabOwnerId));
  });
});
